function [fitresult, gof] = createFitT1(TI, TR, y_data)
%CREATEFIT(TI,TR,Y_DATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : TI
%      Y Input : TR
%      Z Output: y_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Oct-2019 10:47:39


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( TI, TR, y_data );

% Set up fittype and options.
ft = fittype( 'a*(1-2*exp(-x/b)+exp(-y/b))+c', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';

%%%%
opts.Lower = [0 0 -1];
opts.Upper = [10 6 6];
opts.StartPoint = [0.991966876997438 0.526367507137759 0.961046087302673];

%opts.Lower = [0, 0, -1];
%opts.Upper = [10, 10, 6];
%opts.StartPoint = [0.9, 0.5, 0.9];
%%%%

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );
% 
% % % Plot fit with data.
%  figure( 'Name', 'untitled fit 1' );
%  h = plot( fitresult, [xData, yData], zData );
%  legend( h, 'untitled fit 1', 'y_data vs. TI, TR', 'Location', 'NorthEast', 'Interpreter', 'none' );
%  % Label axes
%  xlabel( 'TI', 'Interpreter', 'none' );
%  ylabel( 'TR', 'Interpreter', 'none' );
%  zlabel( 'y_data', 'Interpreter', 'none' );
%  grid on
%  view( -0.2, -1.2 );


