function [fitresult, gof] = createFitT2(TE, y_data)
%CREATEFIT(TE,Y_DATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : TE
%      Y Output: y_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Nov-2019 12:26:05


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( TE, y_data );

% Set up fittype and options.
ft = fittype( 'a*exp(-x/b)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.915735525189067 0.792207329559554 0.512779629734432];

% Fit model to data.
opts.Lower = [0 0];
opts.Upper = [10 6];
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y_data vs. TE', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'TE', 'Interpreter', 'none' );
% ylabel( 'y_data', 'Interpreter', 'none' );
% grid on
